export const mockBrands = {
  data: [
    {
      slug: 'acura',
      name: 'Acura',
      name_en: 'Acura',
      regions: ['cdm', 'chdm', 'eudm', 'medm', 'mxndm', 'russia', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/acura-1622187471.8597765.png',
    },
    {
      slug: 'nissan',
      name: 'Nissan',
      name_en: 'Nissan',
      regions: ['audm', 'cdm', 'chdm', 'eudm', 'jdm', 'ladm', 'medm', 'mxndm', 'nadm', 'russia', 'sadm', 'sam', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/nissan-1632742769.6952765.png',
    },
    {
      slug: 'toyota',
      name: 'Toyota',
      name_en: 'Toyota',
      regions: ['audm', 'cdm', 'chdm', 'eudm', 'jdm', 'ladm', 'medm', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/toyota-1632743807.0095704.png',
    },
    {
      slug: 'nissan',
      name: 'Nissan',
      name_en: 'Nissan',
      regions: ['audm', 'cdm', 'chdm', 'eudm', 'jdm', 'ladm', 'medm', 'mxndm', 'nadm', 'russia', 'sadm', 'sam', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/nissan-1632742769.6952765.png',
    },
    {
      slug: 'hyundai',
      name: 'Hyundai',
      name_en: 'Hyundai',
      regions: ['audm', 'cdm', 'chdm', 'eudm', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/hyundai-1622196052.2252924.png',
    },
    {
      slug: 'land-rover',
      name: 'Land Rover',
      name_en: 'Land Rover',
      regions: ['audm', 'cdm', 'chdm', 'eudm', 'jdm', 'skdm', 'usdm'],
      logo: 'https://cdn.wheel-size.com/automobile/manufacturer/land-rover-1622197056.750649.png',
    },
  ],
};

export const mockModels = {
  data: [
    {
      slug: 'sentra',
      name: 'Sentra',
      name_en: 'Sentra',
      regions: ['cdm', 'ladm', 'medm', 'mxndm', 'nadm', 'russia', 'sam', 'usdm'],
      year_ranges: ['1989-2024'],
    },
    {
      slug: 'serena',
      name: 'Serena',
      name_en: 'Serena',
      regions: ['chdm', 'eudm', 'jdm', 'sam'],
      year_ranges: ['1991-2024'],
    },
    {
      slug: 'silvia',
      name: 'Silvia',
      name_en: 'Silvia',
      regions: ['eudm', 'jdm'],
      year_ranges: ['1983-2002'],
    },
    {
      slug: 'skyline',
      name: 'Skyline',
      name_en: 'Skyline',
      regions: ['jdm'],
      year_ranges: ['1989-2024'],
    },
    {
      slug: '4runner',
      name: '4Runner',
      name_en: '4Runner',
      regions: ['cdm', 'eudm', 'ladm', 'medm', 'usdm'],
      year_ranges: ['1989-2024'],
    },
    {
      slug: '86',
      name: '86',
      name_en: '86',
      regions: ['audm', 'cdm', 'jdm', 'ladm', 'medm', 'sadm', 'sam', 'skdm', 'usdm'],
      year_ranges: ['2012-2024'],
    },
    {
      slug: 'agya',
      name: 'Agya',
      name_en: 'Agya',
      regions: ['ladm', 'nadm', 'sadm', 'sam'],
      year_ranges: ['2013-2025'],
    },
    {
      slug: 'corolla-2',
      name: 'Corolla II',
      name_en: 'Corolla II',
      regions: ['jdm'],
      year_ranges: ['1990-1999'],
    },
    {
      slug: 'corolla-altis',
      name: 'Corolla Altis',
      name_en: 'Corolla Altis',
      regions: ['ladm', 'sam'],
      year_ranges: ['2002-2024'],
    },
    {
      slug: 'corolla-axio',
      name: 'Corolla Axio',
      name_en: 'Corolla Axio',
      regions: ['jdm'],
      year_ranges: ['2006-2024'],
    },
    {
      slug: 'corolla-ceres',
      name: 'Corolla Ceres',
      name_en: 'Corolla Ceres',
      regions: ['jdm'],
      year_ranges: ['1992-1999'],
    },
    {
      slug: 'yaris-l',
      name: 'Yaris L',
      name_en: 'Yaris L',
      regions: ['chdm'],
      year_ranges: ['2013-2022'],
    },
    {
      slug: 'yaris-l-x',
      name: 'Yaris L X',
      name_en: 'Yaris L X',
      regions: ['chdm'],
      year_ranges: ['2020-2022'],
    },
    {
      slug: 'i20',
      name: 'i20',
      name_en: 'i20',
      regions: ['eudm', 'ladm', 'medm', 'nadm', 'sadm', 'sam'],
      year_ranges: ['2008-2025'],
    },
    {
      slug: 'range-rover',
      name: 'Range Rover',
      name_en: 'Range Rover',
      regions: ['audm'],
      year_ranges: ['1970-2025'],
    },
  ],
};

export const mockYears = {
  data: [
    {
      slug: 1989,
      name: 1989,
    },
    {
      slug: 1990,
      name: 1990,
    },
    {
      slug: 1991,
      name: 1991,
    },
    {
      slug: 1992,
      name: 1992,
    },
    {
      slug: 1993,
      name: 1993,
    },
    {
      slug: 1994,
      name: 1994,
    },
    {
      slug: 1995,
      name: 1995,
    },
    {
      slug: 1996,
      name: 1996,
    },
    {
      slug: 1997,
      name: 1997,
    },
    {
      slug: 1998,
      name: 1998,
    },
    {
      slug: 1999,
      name: 1999,
    },
    {
      slug: 2000,
      name: 2000,
    },
    {
      slug: 2001,
      name: 2001,
    },
    {
      slug: 2002,
      name: 2002,
    },
    {
      slug: 2003,
      name: 2003,
    },
    {
      slug: 2004,
      name: 2004,
    },
    {
      slug: 2005,
      name: 2005,
    },
    {
      slug: 2006,
      name: 2006,
    },
    {
      slug: 2007,
      name: 2007,
    },
    {
      slug: 2008,
      name: 2008,
    },
    {
      slug: 2009,
      name: 2009,
    },
    {
      slug: 2010,
      name: 2010,
    },
    {
      slug: 2011,
      name: 2011,
    },
    {
      slug: 2012,
      name: 2012,
    },
    {
      slug: 2013,
      name: 2013,
    },
    {
      slug: 2014,
      name: 2014,
    },
    {
      slug: 2015,
      name: 2015,
    },
    {
      slug: 2016,
      name: 2016,
    },
    {
      slug: 2017,
      name: 2017,
    },
    {
      slug: 2018,
      name: 2018,
    },
    {
      slug: 2019,
      name: 2019,
    },
    {
      slug: 2020,
      name: 2020,
    },
    {
      slug: 2021,
      name: 2021,
    },
    {
      slug: 2022,
      name: 2022,
    },
    {
      slug: 2023,
      name: 2023,
    },
    {
      slug: 2024,
      name: 2024,
    },
  ],
};

export const mockVersions = {
  data: [
    {
      slug: '20fd0c7135',
      name: '1.6',
      generation: {
        slug: '26751be118',
        name: 'IV (B14)',
        bodies: [
          {
            image: 'https://cdn.wheel-size.com/automobile/body/nissan-sentra-1995-1999-1455895661.21.jpg',
          },
        ],
      },
    },
    {
      slug: '1087e24f05',
      name: '1.6',
      generation: {
        slug: 'f60f6b0d12',
        name: 'III (B13)',
        bodies: [
          {
            image: 'https://cdn.wheel-size.com/automobile/body/nissan-sentra-1995-2016-1627290951.994609.jpg',
          },
        ],
      },
    },
    {
      slug: '372ab54d47',
      name: '2.0',
      generation: {
        slug: '26751be118',
        name: 'IV (B14)',
        bodies: [
          {
            image: 'https://cdn.wheel-size.com/automobile/body/nissan-sentra-1995-1999-1455895661.21.jpg',
          },
        ],
      },
    },
    {
      slug: 'f1c5911ee2',
      name: '4.0',
      generation: {
        slug: '2db9f30839',
        name: 'IV Facelift',
        platform: '',
        start: 2006,
        end: 2009,
        bodies: [
          {
            slug: 'a3e14106dc',
            name: 'Closed Off-Road Vehicle, 5d (N210)',
            image: 'https://cdn.wheel-size.com/automobile/body/toyota-4runner-2006-2009-1682429251.3025696.jpg',
          },
        ],
      },
    },
    {
      slug: '947d516252',
      name: '4.7',
      generation: {
        slug: '2db9f30839',
        name: 'IV Facelift',
        platform: '',
        start: 2006,
        end: 2009,
        bodies: [
          {
            slug: 'a3e14106dc',
            name: 'Closed Off-Road Vehicle, 5d (N210)',
            image: 'https://cdn.wheel-size.com/automobile/body/toyota-4runner-2006-2009-1682429251.3025696.jpg',
          },
        ],
      },
    },
  ],
};

export const mockMeasures = {
  data: [
    {
      wheels: [
        {
          is_stock: true,
          showing_fp_only: false,
          is_extra_load_tires: false,
          is_recommended_for_winter: false,
          is_runflat_tires: false,
          is_pressed_steel_rims: false,
          front: {
            rim: '8.5Jx19 ET47',
            rim_diameter: 19.0,
            rim_width: 8.5,
            rim_offset: 47.0,
            tire_full: '255/55ZR19 111Y',
            tire: '255/55ZR19',
            load_index: 111,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 255.0,
            tire_aspect_ratio: 55.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 255,
            tire_diameter_mm: 763,
            tire_weight_kg: 13.68,
          },
          rear: {
            rim: '9.5Jx19 ET54',
            rim_diameter: 19.0,
            rim_width: 9.5,
            rim_offset: 54.0,
            tire_full: '275/50ZR19 112Y',
            tire: '275/50ZR19',
            load_index: 112,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 275.0,
            tire_aspect_ratio: 50.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 275,
            tire_diameter_mm: 758,
            tire_weight_kg: 14.45,
          },
        },
        {
          is_stock: false,
          showing_fp_only: false,
          is_extra_load_tires: false,
          is_recommended_for_winter: false,
          is_runflat_tires: false,
          is_pressed_steel_rims: false,
          front: {
            rim: '9Jx20 ET50',
            rim_diameter: 20.0,
            rim_width: 9.0,
            rim_offset: 50.0,
            tire_full: '275/45ZR20 110Y',
            tire: '275/45ZR20',
            load_index: 110,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 275.0,
            tire_aspect_ratio: 45.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 275,
            tire_diameter_mm: 756,
            tire_weight_kg: 14.22,
          },
          rear: {
            rim: '10.5Jx20 ET64',
            rim_diameter: 20.0,
            rim_width: 10.5,
            rim_offset: 64.0,
            tire_full: '305/40ZR20 112Y',
            tire: '305/40ZR20',
            load_index: 112,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 305.0,
            tire_aspect_ratio: 40.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 305,
            tire_diameter_mm: 752,
            tire_weight_kg: 15.45,
          },
        },
        {
          is_stock: false,
          showing_fp_only: false,
          is_extra_load_tires: false,
          is_recommended_for_winter: false,
          is_runflat_tires: false,
          is_pressed_steel_rims: false,
          front: {
            rim: '9.5Jx21 ET46',
            rim_diameter: 21.0,
            rim_width: 9.5,
            rim_offset: 46.0,
            tire_full: '285/40ZR21 109Y',
            tire: '285/40ZR21',
            load_index: 109,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 285.0,
            tire_aspect_ratio: 40.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 285,
            tire_diameter_mm: 761,
            tire_weight_kg: 14.62,
          },
          rear: {
            rim: '11Jx21 ET58',
            rim_diameter: 21.0,
            rim_width: 11.0,
            rim_offset: 58.0,
            tire_full: '315/35ZR21 111Y',
            tire: '315/35ZR21',
            load_index: 111,
            speed_index: 'Y',
            tire_pressure: null,
            tire_sizing_system: 'metric',
            tire_construction: 'R',
            tire_width: 315.0,
            tire_aspect_ratio: 35.0,
            tire_diameter: null,
            tire_section_width: null,
            tire_is_82series: false,
            tire_alpha_numeric: null,
            tire_width_mm: 315,
            tire_diameter_mm: 757,
            tire_weight_kg: 15.86,
          },
        },
      ],
    },
  ],
};
